/* Generated By:JavaCC: Do not edit this line. GologParserConstants.java */
package incr.golog.syntax.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GologParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAR_OP = 6;
  /** RegularExpression Id. */
  int PAR_CL = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int ENDIF = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int ENDWHILE = 17;
  /** RegularExpression Id. */
  int PROC = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int ENDPROC = 20;
  /** RegularExpression Id. */
  int PI = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int QUESTIONMARK = 23;
  /** RegularExpression Id. */
  int COLON = 24;
  /** RegularExpression Id. */
  int PIPE = 25;
  /** RegularExpression Id. */
  int STAR = 26;
  /** RegularExpression Id. */
  int ACTION = 27;
  /** RegularExpression Id. */
  int PRECONDITIONS = 28;
  /** RegularExpression Id. */
  int ADD = 29;
  /** RegularExpression Id. */
  int DEL = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int NUMINT = 32;
  /** RegularExpression Id. */
  int NUMFLOAT = 33;
  /** RegularExpression Id. */
  int VAR = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endIf\"",
    "\"while\"",
    "\"do\"",
    "\"endWhile\"",
    "\"proc\"",
    "\",\"",
    "\"endProc\"",
    "\"pi\"",
    "\".\"",
    "\"?\"",
    "\":\"",
    "\"|\"",
    "\"*\"",
    "\"action\"",
    "\"preconditions\"",
    "\"add\"",
    "\"del\"",
    "<ID>",
    "<NUMINT>",
    "<NUMFLOAT>",
    "<VAR>",
  };

}
